name: CI

on:
  push:
  pull_request:

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] # , macos-latest, windows-latest]
        python-version: ["3.10"] # , "3.11", "3.12"]

    name: Test
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest

    - name: Run pytest
      run: |
        pytest
  
  create-release:
    needs: run-tests
    if: ${{ success(needs.run-tests) }}  # Run only if run-tests job succeeded
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"  # Choose a specific Python version

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Run Release Script
      run: |
        python create_release.py

  